### ISSUE TITLE
Cannot reproduce with default parameters

### ISSUE THREAD

**Issue by ZzzzMe** [Tongzhou0101/NNSplitter#1]
result <mobilenet_cifar_rnn.pth> seems to be as same as the pre_trained weights...How can I get an obfuscated model?

**Comment by Tongzhou0101** [comment]
For your problem, the reason could be that we use different pre-trained models with different weight distributions. However, you can still apply our method to your model by adjusting the parameters B_list and args.eps in controller_rnn.py (corresponding to $c$ and $\epsilon$ in figure 2 in the paper), which can be determined after you profile the weights distributions of your model. For more details about setting these parameters, you can check _mask generator_ in section 3.1.
